# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#source 'https://github.com/FengruiJian/BPSpecs.git'

platform :ios, "8.0"
inhibit_all_warnings!

target 'PBM' do
#pod 'BPcomponent'
pod 'JAnalytics'
end
